APPNAME=cedit
LIBAPP_SRC=../libdemo/colormod.c ../libdemo/gamma.c ../libdemo/getset.c ../libdemo/grey.c ../libdemo/getapixel.c ../demo_include/democolors.c
OLD_CODE_WARN_OFF_EXTRA=-Wno-incompatible-pointer-types
include ../Make/make_demo_applib.mk