APPNAME=bounce
EMLNKR=--preload-file canstick.bin --preload-file doughnut.bin --preload-file logo.bin --preload-file martini.bin --preload-file vw.bin --preload-file x29.bin
include ../Make/make_demo.mk