APPNAME=buttonfly
APPARGS=menu_demos
APPCMDS=cp web/buttonfly.js web/buttonfly.wasm web/buttonfly.data ../../sgi-demos.github.io
EMLNKR=--preload-file menus/menu --preload-file menus/m_demos --preload-file menus/m_more_demos --preload-file menus/m_bounce

include ../build/make_demo.mk